import type { Part } from './part.ts';

export const unitName = (prefix: string, part: string): string => `${prefix}${part}.service`;

/** How long a `ready` check may keep saying "not yet" before the part is failed. */
export const READY_TIMEOUT_MS = 60_000;

/** systemd unit-file quoting: C escapes inside "", and `%` starts a specifier. */
const quote = (s: string): string =>
  s.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('%', '%%');

/**
 * The translation (Part -> unit file). Byte-for-byte deterministic: `up`
 * compares the file on disk against this string to decide whether anything
 * actually changed, which is what keeps `daemon-reload` out of the no-op path.
 *
 * O1: `needs` becomes BOTH `Requires=` (existence — pull the dependency up,
 * take it down with the dependency) and `After=` (order). `After=` alone would
 * order without guaranteeing the dependency runs at all.
 */
export function unitText(
  part: Part, prefix: string, traceDir: string, readyTimeoutMs = READY_TIMEOUT_MS,
): string {
  const deps = part.needs.map((d) => unitName(prefix, d)).join(' ');
  const trace = `${traceDir}/${part.name}.log`;
  return [
    `# Generated by theseus from the Part declaration. Do not edit: 'theseus up' rewrites it.`,
    `[Unit]`,
    `Description=Theseus part ${part.name}`,
    ...(deps ? [`Requires=${deps}`, `After=${deps}`] : []),
    ``,
    `[Service]`,
    `Type=exec`,
    `ExecStart=/bin/sh -c "${quote(part.command)}"`,
    // I5b: with `Type=exec` the unit stays `activating` until every
    // `ExecStartPost=` has exited, so the wait for readiness IS the `activating`
    // state — which is what makes "still coming up" something systemd reports
    // rather than something we guess. The part never learns systemd exists
    // (contrast `Type=notify`, which would mean editing the part itself).
    // No `ready` declared, no lines at all: the part keeps the old behaviour of
    // being called up the moment its process is.
    ...(part.ready === undefined ? [] : [
      `ExecStartPost=/bin/sh -c "until ${quote(part.ready)}; do sleep 0.1; done"`,
      // P2 again, for the other direction: the wait is bounded. When the budget
      // runs out the unit goes `failed` (E3) — never `active`, and never a wait
      // with no end.
      `TimeoutStartSec=${readyTimeoutMs}ms`,
    ]),
    `StandardOutput=append:${trace}`,
    `StandardError=append:${trace}`,
    // P2: bounded worst case for `down`. systemd SIGKILLs the whole control
    // group at this point; if that still fails the unit goes `failed` (E3).
    `TimeoutStopSec=10`,
    ``,
  ].join('\n');
}
